# -*- coding: utf-8 -*-
"""Join-Sidra-GeoBR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWjA8DU4biygpGo8E_f1nPdSOO7oO6cf

# 1. Introdução

Este notebook tem como objetivo **coletar e tratar dados do SIDRA/IBGE utilizando a biblioteca `sidraPy`**, facilitando a análise estatística de indicadores brasileiros.

## ℹ️ O que é o SIDRA?

O **SIDRA (Sistema IBGE de Recuperação Automática)** é uma plataforma do IBGE que disponibiliza dados estatísticos sobre diversos temas do Brasil, como demografia, economia e agricultura. Esses dados podem ser acessados via API para análises automatizadas.

## 🐍 Sobre a biblioteca `sidraPy`

A **`sidraPy`** é uma biblioteca Python desenvolvida pela comunidade que simplifica o processo de consulta à API do SIDRA. Ela permite fazer requisições diretas aos dados do IBGE e obtê-los em formatos prontos para análise (como DataFrames do pandas).

**Principais benefícios:**
- Automatiza o download de dados diretamente da base do IBGE.
- Transforma as informações em estruturas Python (dicionários, DataFrames).
- Permite personalizar filtros como tabela, período, localidade e variáveis.

## ⚙️ Personalizando consultas

A principal função da biblioteca é o `get_table()`, que permite definir de forma flexível:
- **Tabela**: o código da tabela SIDRA a ser consultada.
- **Período**: anos ou meses específicos dos dados.
- **Localidade**: nível territorial (Brasil, regiões, estados, municípios).
- **Variáveis** e classificações específicas.

Com isso, é possível obter exatamente o recorte estatístico desejado para sua análise.

# 2. Instalação e importação das bibliotecas
"""
import sidrapy
import pandas as pd
import plotly as plt
import geobr as geo
import geopandas as gpd
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

"""# 3. Parâmetros da coleta
- Tabela: 6417 - Pessoas de 10 anos ou mais de idade, por cor ou raça, segundo o sexo e a religião
- Nível territorial: Unidade da Federação
- Período: 2022
- Variáveis: 140
- Classificadores: 86(Cor/raça), 2(Sexo) e 133(Religião)

Exemplos de tabelas:
*   10198 - 	Pessoas de 15 anos ou mais de idade por religião, segundo os grupos de idade e alfabetização
*   9542 - Pessoas de 15 anos ou mais de idade, total e as alfabetizadas, por sexo, cor ou raça e grupos de idade
*   6417 - Pessoas de 10 anos ou mais de idade, por cor ou raça, segundo o sexo e a religião
*   10147	- População residente, total e diagnosticada com autismo, por cor ou raça
*   9591 - Número de microempreendedores individuais (MEIs) e média de idade, por sexo, faixas de idade, nacionalidade/país de origem, cor ou raça, etc
"""

df = sidrapy.get_table(
    table_code='6417',
    territorial_level='3',    # Unidade da Federação (UF)
    ibge_territorial_code='all',
    period='2022',
    variable='140',       # Pessoas de 10 anos ou mais de idade (Pessoas)
    format='pandas',
    classifications={"133": "95263,95277,2826,2827,95274,95275,2836,12890,2837", "2": "4,5", "86": "2776,2777,2778,2779,2780"},
)

df.head()

state = geo.read_state(code_state="all", year=2020)
state.head()

df.shape

state.shape

"""# 4. Tratamento dos dados"""

# Header da tabela está na linha 0
df.iloc[:1]

# Adicionando a linha 0 como nome das colunas
df.columns = df.iloc[0]
df = df[1:].reset_index(drop=True)
df.head(3)

# Lista das colunas a serem removidas
colunas_a_remover = [
    'Unidade de Medida (Código)',
    'Unidade de Medida',
    'Ano (Código)',
    'Variável (Código)',
    'Religião (Código)',
    'Sexo (Código)',
    'Cor ou raça (Código)'
]

# Remove as colunas do DataFrame
df = df.drop(columns=colunas_a_remover, errors='ignore')
df.head()

# Removendo valores inexistentes
df_filtered = df[df['Valor'] != '-']

# Convertendo a coluna de Valor para int
df_filtered['Valor'] = df_filtered['Valor'].astype(int)

# Reduzindo o nome da religião Católica
df_filtered['Religião'] = df_filtered['Religião'].replace('Católica Apostólica Romana', 'Católica')

# Deixando o mesmo nome da outra coluna
df_filtered = df_filtered.rename(columns={'Unidade da Federação (Código)': 'code_state'})

# Convertendo o valor float para object
state['code_state'] = state['code_state'].astype(int).astype(str)

merged_df = pd.merge(state, df_filtered, on='code_state', how='inner')
merged_df.head()

merged_df.columns

merged_df.info()
# merged_df['Religião'] = merged_df['Religião'].replace(['sem declaracao', 'nao sabe'], 'outras religiosidades')
merged_df['Religião'] = merged_df['Religião'].replace(['Sem declaração', 'Não sabe'], 'Outras religiosidades')
merged_df.to_csv('merged_df.csv', index=False)

"""# 5. Gráficos

## Estado x Religião
"""

def escala_formato(value):
    if value >= 1_000_000:
        return f'{value / 1_000_000:.2f} M'
    elif value >= 1000:
        return f'{value / 1000:.0f} K'
    else:
        return f'{value:.0f}'

# Filtrando o DataFrame para o estado selecionado
state_name = "Pernambuco"
df_state = merged_df[merged_df['Unidade da Federação'] == state_name].copy()

# Agrupando por Religião pela soma
religiao_group = df_state.groupby('Religião')['Valor'].sum().reset_index()

# Criando coluna formatada com escala personalizada
religiao_group['Valor_formatado'] = religiao_group['Valor'].apply(escala_formato)

# Convertendo Valor para milhões para manter o eixo
religiao_group['Valor_M'] = religiao_group['Valor'] / 1_000_000

# Ordenando
religiao_group.sort_values(by='Valor_M', ascending=False, inplace=True)

# Plotando o gráfico
fig1 = px.bar(
    religiao_group,
    x='Religião',
    y='Valor_M',
    title=f'Distribuição da População por Religião em {state_name}',
    text='Valor_formatado',
    color='Religião',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig1.update_layout(
    xaxis_tickangle=-45,
    xaxis_title=None,
    yaxis_title=None,
    yaxis=dict(showticklabels=False, showgrid=True, zeroline=False),
    plot_bgcolor='white'
)
fig1.update_traces(textposition='outside')

fig1.show()

"""## Estado x Sexo"""

# Filtrando o DataFrame para o estado selecionado
state_name = "São Paulo"
df_state = merged_df[merged_df['Unidade da Federação'] == state_name].copy()

# Agrupando por Sexo pela soma do Valor
sexo_group = df_state.groupby('Sexo')['Valor'].sum().reset_index()

# Plotando a figura
fig2 = px.pie(
    sexo_group,
    names='Sexo',
    values='Valor',
    title= f'% da População por Sexo em {state_name}',
    color_discrete_sequence=px.colors.qualitative.Set3
)

# Elementos de design do gráfico
fig2.update_traces(textinfo='percent+label', pull=[0.05, 0])
fig2.update_layout(
    margin=dict(l=20, r=20, t=50, b=20),
    height=400,
    width=600
)
fig2.show()

"""# Cor/Raça x Estado"""

# Filtrando o DataFrame para o estado selecionado
state_name = "Bahia"
df_state = merged_df[merged_df['Unidade da Federação'] == state_name].copy()

# Agrupando por Cor/Raça
cor_group = df_state.groupby('Cor ou raça')['Valor'].sum().reset_index()

# Criando coluna formatada
cor_group['Valor_formatado'] = cor_group['Valor'].apply(escala_formato)

# Convertendo Valor para milhões para manter o eixo fixo em M
cor_group['Valor_M'] = cor_group['Valor'] / 1_000_000

# Ordenando
cor_group.sort_values(by='Valor_M', ascending=False, inplace=True)

# Plotando o gráfico
fig3 = px.bar(
    cor_group,
    x='Cor ou raça',
    y='Valor_M',
    title=f'Distribuição da População por Cor/Raça em {state_name}',
    text='Valor_formatado',
    color='Cor ou raça',
    color_discrete_sequence=px.colors.qualitative.Pastel2
)

fig3.update_layout(
    xaxis_tickangle=-45,
    xaxis_title=None,
    yaxis_title=None,
    yaxis=dict(showticklabels=False, showgrid=True, zeroline=False),
    plot_bgcolor='white'
)
fig3.update_traces(textposition='outside')
fig3.show()


"""# Sexo x Raça por Estado"""
# Filtrando o DataFrame para o estado selecionado
state_name = "Pernambuco"
df_state = merged_df[merged_df['Unidade da Federação'] == state_name].copy()

df_sexo_cor = df_state.groupby(['Sexo', 'Cor ou raça'])['Valor'].sum().reset_index()

fig4 = px.bar(df_sexo_cor,
             x='Sexo',
             y='Valor',
             color='Cor ou raça',
             title=f'Distribuição da População por Cor/Raça e Sexo - {state_name}',
             labels={'Valor': 'População'},
             color_discrete_sequence=px.colors.qualitative.Vivid,
             text='Valor')

fig4.update_layout(barmode='stack', 
                    xaxis_tickangle=-45,
                    margin=dict(l=20, r=20, t=50, b=20),
                    height=500,
                    width=600)
fig4.update_traces(texttemplate='%{text:.2s}', textposition='outside')
fig4.show()